### ISSUE TITLE
other Setup Files

### ISSUE THREAD

**Issue by NorbertBauer** [SaadKhamis/IntuneWinAppUtilGUI#1]
Hi

Thank you for this nice tool. It works well and makes it a little easier, to create the Win32 Apps.

But why are you only allow EXE and MSI für the Setupfile? We often use CMD/BAT and also in some cases PS1 and very rare also VBS.
Would be greate, if you can allow these filetypes too. And maybe some others, because anything Windows can execute, can be used as install command here.

Thanks
Norbert

**Comment by SaadKhamis** [comment]
Hello Norbert,
Thank you for the feedback.
Others asked for the same. I will update the tool and post a new version.

**Comment by SaadKhamis** [comment]
"Setup file:" now allows for more file types, "Setup (*.bat;*.cmd;*.exe;*.msi;*.ps1)|All types (*.*)".
